### PR TITLE
Add excess block metric

### PR DESCRIPTION
**Pull request by kevin-bruhwiler**
Could one of you, if you have time, run the simulation and see if the results make sense to you?

### CODE REVIEW

**Comment by gsoosk** [comment]
I will run the simulation tomorrow night if no one has done it by then.

**Review by thebah — APPROVED** [review]
I think it is OK to merge now or maybe wait until we finish discussing it as planned on Thursday's meeting.  I think both are OK.

**Comment by kevin-bruhwiler** [comment]
I pulled this branch and my results are looking fine. Do you maybe want to clear it and pull it again to double check that nothing got changed?

**Comment by thebah** [comment]
I did pull it again too and it still shows the same results on my machine. I went back to the main branch and run it, I was able to get the "number of forks" figure only, which also looks different than the one in Slack. I haven't touched the code I mainly edited the path to the configuration files.

**Pull request merged**
